[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
leanback = "1.2.0"
glide = "4.11.0"
glide-compiler = "4.11.0"
coil-compose = "2.7.0"
compose-bom = "2024.11.00"
navigation-compose = "2.8.4"
tv-foundation = "1.0.0-alpha11"
tv-material = "1.0.0"
lifecycle-runtime-ktx = "2.8.7"
activity-compose = "1.9.3"
foundation = "1.7.0-beta07"
ui = "1.7.0-beta07"
ktor = "2.3.12"
serialization = "1.6.3"
compose-compiler = "1.5.8"
media3 = "1.8.0"
jellyfin-media3-ffmpeg = "1.8.0+1"
lottie = "6.1.0"
palette = "1.0.0"
nanojson = "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
jsoup = "1.18.1"
jsr305 = "3.0.2"
protobuf = "3.25.1" # mental check: compatibility with android
rhino = "1.8.0"
protobufPlugin = "0.9.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide-compiler" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tv-foundation" }
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tv-material" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
    media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
    media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
    media3-exoplayer-smoothstreaming = { module = "androidx.media3:media3-exoplayer-smoothstreaming", version.ref = "media3" }
    media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
    media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3" }
    media3-ui-leanback = { module = "androidx.media3:media3-ui-leanback", version.ref = "media3" }
    media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
    media3-extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3" }
    media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
    media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
    media3-datasource-cronet = { module = "androidx.media3:media3-datasource-cronet", version.ref = "media3" }
    media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }
    media3-effect = { module = "androidx.media3:media3-effect", version.ref = "media3" }
    media3-muxer = { module = "androidx.media3:media3-muxer", version.ref = "media3" }
jellyfin-media3-ffmpeg-decoder = { module = "org.jellyfin.media3:media3-ffmpeg-decoder", version.ref = "jellyfin-media3-ffmpeg" }
lottieCompose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
nanojson = { module = "com.github.TeamNewPipe:nanojson", version.ref = "nanojson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
rhino-engine = { module = "org.mozilla:rhino-engine", version.ref = "rhino" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
