/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.schabi.newpipe.extractor.timeago;

import org.schabi.newpipe.extractor.timeago.patterns.*;
import java.util.HashMap;
import java.util.Map;

public class PatternMap {
    private static final Map<String, PatternsHolder> patternMap = new HashMap<>();

    static {
        patternMap.put("ar", ar.getInstance());
        patternMap.put("az", az.getInstance());
        patternMap.put("bg", bg.getInstance());
        patternMap.put("ca", ca.getInstance());
        patternMap.put("cs", cs.getInstance());
        patternMap.put("el", el.getInstance());
        patternMap.put("en_GB", en_GB.getInstance());
        patternMap.put("es_US", es_US.getInstance());
        patternMap.put("eu", eu.getInstance());
        patternMap.put("fil", fil.getInstance());
        patternMap.put("fr_CA", fr_CA.getInstance());
        patternMap.put("gl", gl.getInstance());
        patternMap.put("hr", hr.getInstance());
        patternMap.put("hu", hu.getInstance());
        patternMap.put("hy", hy.getInstance());
        patternMap.put("id", id.getInstance());
        patternMap.put("is", is.getInstance());
        patternMap.put("ja", ja.getInstance());
        patternMap.put("ka", ka.getInstance());
        patternMap.put("ko", ko.getInstance());
        patternMap.put("ky", ky.getInstance());
        patternMap.put("mk", mk.getInstance());
        patternMap.put("ml", ml.getInstance());
        patternMap.put("mr", mr.getInstance());
        patternMap.put("my", my.getInstance());
        patternMap.put("ne", ne.getInstance());
        patternMap.put("pa", pa.getInstance());
        patternMap.put("pt", pt.getInstance());
        patternMap.put("pt_PT", pt_PT.getInstance());
        patternMap.put("ru", ru.getInstance());
        patternMap.put("sk", sk.getInstance());
        patternMap.put("te", te.getInstance());
        patternMap.put("th", th.getInstance());
        patternMap.put("tr", tr.getInstance());
        patternMap.put("uz", uz.getInstance());
        patternMap.put("vi", vi.getInstance());
        patternMap.put("zh_CN", zh_CN.getInstance());
        patternMap.put("zh_HK", zh_HK.getInstance());
        patternMap.put("zh_TW", zh_TW.getInstance());
        patternMap.put("zu", zu.getInstance());
    }

    public static PatternsHolder getPattern(final String languageCode) {
        return patternMap.get(languageCode);
    }
}
