const root=document.querySelector('#app');
const state={server:localStorage.veloraServer||'',token:localStorage.veloraToken||'',userId:'',items:[],query:''};
const base=()=>state.server.replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=(path,options={})=>fetch(`${base()}${path}`,{...options,headers:{Accept:'application/json','Content-Type':'application/json','X-Emby-Token':state.token,...(options.headers||{})}}).then(async response=>{if(!response.ok)throw Error(`Jellyfin respondió ${response.status}`);return response.status===204?null:response.json()});
const image=id=>`${base()}/Items/${encodeURIComponent(id)}/Images/Primary?api_key=${encodeURIComponent(state.token)}&maxWidth=600`;
const stream=id=>`${base()}/Videos/${encodeURIComponent(id)}/stream?static=true&api_key=${encodeURIComponent(state.token)}`;

function login(){root.innerHTML=`<section class="login"><h1>Velora</h1><p class="muted">Conecta tu servidor Jellyfin</p><input id="server" value="${esc(state.server)}" placeholder="https://servidor:8096" autocomplete="url"><input id="user" placeholder="Usuario" autocomplete="username"><input id="password" type="password" placeholder="Contraseña" autocomplete="current-password"><button class="primary" id="signIn">Iniciar sesión</button><p id="loginError" class="error" role="alert"></p></section>`;document.querySelector('#signIn').onclick=authenticate;document.querySelector('#password').onkeydown=e=>e.key==='Enter'&&authenticate()}
async function authenticate(){const error=document.querySelector('#loginError');try{state.server=document.querySelector('#server').value.trim();const username=document.querySelector('#user').value.trim();const response=await fetch(`${base()}/Users/AuthenticateByName`,{method:'POST',headers:{'Content-Type':'application/json','X-Emby-Authorization':'MediaBrowser Client="Velora Web", Device="Browser", DeviceId="velora-web", Version="1.0"'},body:JSON.stringify({Username:username,Password:document.querySelector('#password').value})});if(!response.ok)throw Error('No se pudo iniciar sesión');const data=await response.json();state.token=data.AccessToken;state.userId=data.User?.Id||'';Object.assign(localStorage,{veloraServer:state.server,veloraToken:state.token,veloraUser:username,veloraUserId:state.userId});await renderApp()}catch(e){error.textContent=e.message}}
async function loadItems(){if(!state.userId){const me=await api('/Users/Me');state.userId=me.Id;localStorage.veloraUserId=state.userId}const params=new URLSearchParams({Recursive:'true',IncludeItemTypes:'Movie,Series,LiveTvChannel',SortBy:'DateCreated',SortOrder:'Descending',Limit:'150',Fields:'Overview,ProductionYear,PrimaryImageAspectRatio'});const data=await api(`/Users/${state.userId}/Items?${params}`);state.items=data.Items||[]}
function section(title,items){if(!items.length)return '';return `<section><h2>${title}</h2><div class="grid">${items.map(item=>`<article class="card" tabindex="0" role="button" data-id="${esc(item.Id)}"><img loading="lazy" src="${image(item.Id)}" alt=""><div class="label">${esc(item.Name)}</div></article>`).join('')}</div></section>`}
function bindCards(){document.querySelectorAll('.card').forEach(card=>{const open=()=>openItem(card.dataset.id);card.onclick=open;card.onkeydown=e=>(e.key==='Enter'||e.key===' ')&&open()})}
function openItem(id){const item=state.items.find(x=>x.Id===id);if(!item)return;root.insertAdjacentHTML('beforeend',`<div class="modal" id="details"><div class="modal-card"><button class="close" id="detailsClose">Atrás</button><img class="detail-image" src="${image(item.Id)}" alt=""><h1>${esc(item.Name)}</h1><p class="muted">${esc(item.ProductionYear||'')} ${item.Type==='Series'?'· Serie':''}</p><p>${esc(item.Overview||'Sin descripción disponible.')}</p><button class="primary" id="playItem">Reproducir</button></div></div>`);document.querySelector('#detailsClose').onclick=()=>document.querySelector('#details').remove();document.querySelector('#playItem').onclick=()=>{document.querySelector('#details').remove();play(item)}}
function play(item){root.insertAdjacentHTML('beforeend',`<div class="video-wrap" id="player"><video controls autoplay playsinline src="${stream(item.Id)}"></video><div class="video-controls"><button id="fullscreen">Pantalla completa</button><button id="playerClose">Cerrar</button></div></div>`);const player=document.querySelector('#player'),video=player.querySelector('video');document.querySelector('#playerClose').onclick=()=>player.remove();document.querySelector('#fullscreen').onclick=()=>video.requestFullscreen?.();video.onerror=()=>toast('El navegador no puede reproducir este formato directamente.')}
function toast(message){root.insertAdjacentHTML('beforeend',`<div class="toast">${esc(message)}</div>`);setTimeout(()=>document.querySelector('.toast')?.remove(),4000)}
function renderHome(){const query=state.query.toLowerCase(),items=state.items.filter(x=>!query||x.Name.toLowerCase().includes(query)),movies=items.filter(x=>x.Type==='Movie'),series=items.filter(x=>x.Type==='Series'),live=items.filter(x=>x.Type==='LiveTvChannel');document.querySelector('#content').innerHTML=`<div class="hero"><h1>Tu biblioteca</h1><p class="muted">Películas, series y televisión en directo</p><div class="row"><input class="search" id="query" value="${esc(state.query)}" placeholder="Buscar películas y series"><button class="primary" id="search">Buscar</button></div></div><nav class="tabs"><button class="active" data-tab="all">Todo</button><button data-tab="movies">Películas</button><button data-tab="series">Series</button>${live.length?'<button data-tab="live">Televisión en directo</button>':''}</nav><div id="results">${section('Películas',movies)}${section('Series',series)}${section('Televisión en directo',live)}</div>`;const submit=()=>{state.query=document.querySelector('#query').value;renderHome()};document.querySelector('#search').onclick=submit;document.querySelector('#query').onkeydown=e=>e.key==='Enter'&&submit();document.querySelectorAll('[data-tab]').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const view=tab.dataset.tab;document.querySelector('#results').innerHTML=view==='movies'?section('Películas',movies):view==='series'?section('Series',series):view==='live'?section('Televisión en directo',live):`${section('Películas',movies)}${section('Series',series)}${section('Televisión en directo',live)}`;bindCards()});bindCards()}
async function renderApp(){if(!state.token)return login();root.innerHTML='<div class="shell"><header><div class="brand">Velora</div><div class="actions"><button id="refresh">Actualizar</button><button id="logout">Salir</button></div></header><div id="content"><div class="empty">Cargando biblioteca…</div></div></div>';document.querySelector('#logout').onclick=()=>{localStorage.removeItem('veloraToken');state.token='';login()};document.querySelector('#refresh').onclick=async()=>{await loadItems();renderHome()};try{await loadItems();renderHome()}catch(e){document.querySelector('#content').innerHTML=`<div class="error">${esc(e.message)}<br><button class="primary" id="retry">Reintentar</button></div>`;document.querySelector('#retry').onclick=renderApp}}
state.userId=localStorage.veloraUserId||'';renderApp();
